import { NextResponse } from "next/server";
import { z } from "zod";
import { getCustomerSession } from "@/lib/auth/customer-session";
import { getDeliveryQuote } from "@/lib/delivery/delivery-store";
import { createTamaraCheckout, TamaraError } from "@/lib/payments/tamara";
import { prisma } from "@/lib/prisma";

const schema = z.object({ addressId: z.string().min(1), items: z.array(z.object({ productId: z.string().min(1), quantity: z.number().int().positive() })).min(1) });
const money = (amount: number) => ({ amount: amount.toFixed(2), currency: "AED" });
export async function POST(request: Request) {
 const session = await getCustomerSession(); const parsed = schema.safeParse(await request.json().catch(() => null));
 if (!session?.sub) return NextResponse.json({ message: "Please sign in to place your order." }, { status: 401 }); if (!parsed.success) return NextResponse.json({ message: "Your order is incomplete. Please review your items and delivery address." }, { status: 400 });
 let orderId: string | null = null;
 try {
  const result = await prisma.$transaction(async (tx) => { const customer = await tx.customer.findUnique({ where: { id: session.sub } }); const address = await tx.customerAddress.findFirst({ where: { id: parsed.data.addressId, customerId: session.sub } }); const ids = parsed.data.items.map((item) => item.productId); if (!customer || !address) throw new Error("ADDRESS_NOT_FOUND"); if (new Set(ids).size !== ids.length) throw new Error("PRODUCT_UNAVAILABLE"); const products = await tx.product.findMany({ where: { id: { in: ids }, status: "Active" }, include: { category: true } }); if (products.length !== ids.length) throw new Error("PRODUCT_UNAVAILABLE"); const lines = parsed.data.items.map((item) => { const product = products.find((candidate) => candidate.id === item.productId)!; const quantity = product.type === "Animal" ? 1 : item.quantity; if ((product.type === "Animal" && (item.quantity !== 1 || product.isSold)) || (product.type === "Accessory" && product.quantity < quantity)) throw new Error(product.type === "Animal" ? "PET_SOLD" : "OUT_OF_STOCK"); return { product, quantity, unitPrice: Number(product.salePrice ?? product.regularPrice) }; }); const subtotal = lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0); const quote = await getDeliveryQuote(tx, { emirate: address.emirate, area: address.area, subtotal }); if (!quote) throw new Error("DELIVERY_UNAVAILABLE"); const total = subtotal + quote.fee; const orderNumber = `RC-${Date.now().toString().slice(-8)}-${Math.floor(Math.random() * 900 + 100)}`; const order = await tx.order.create({ data: { orderNumber, customerId: customer.id, customerName: customer.name, email: customer.email, phone: address.phone || customer.phone, shippingAddressId: address.id, subtotal, deliveryFee: quote.fee, total, paymentMethod: "Tamara", paymentStatus: "Pending", orderStatus: "Pending", items: { create: lines.map((line) => ({ productId: line.product.id, productName: line.product.name, quantity: line.quantity, unitPrice: line.unitPrice })) }, payment: { create: { provider: "Tamara", method: "Tamara", status: "Pending", amount: total, currency: "AED" } } }, include: { items: true } }); return { order, customer, address, lines, deliveryFee: quote.fee }; });
  orderId = result.order.id; const root = (process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000").replace(/\/$/, ""); const names = result.customer.name.trim().split(/\s+/); const checkout = await createTamaraCheckout({ order_reference_id: result.order.orderNumber, order_number: result.order.orderNumber, total_amount: money(Number(result.order.total)), shipping_amount: money(result.deliveryFee), tax_amount: money(0), items: result.lines.map(({ product, quantity, unitPrice }) => ({ name: product.name, quantity, reference_id: product.id, sku: product.sku, type: "Physical", unit_price: money(unitPrice), total_amount: money(unitPrice * quantity) })), consumer: { first_name: names[0] || result.customer.name, last_name: names.slice(1).join(" ") || "Customer", email: result.customer.email, phone_number: result.order.phone }, country_code: "AE", description: `Royal Chins order ${result.order.orderNumber}`, merchant_url: { success: `${root}/checkout/confirmation?order=${encodeURIComponent(result.order.orderNumber)}&tamara=1`, failure: `${root}/checkout/payment?tamara=failed`, cancel: `${root}/checkout/payment?tamara=cancelled`, notification: `${root}/api/store/tamara/webhook` }, platform: "Royal Chins", locale: "en_US" });
  await prisma.payment.update({ where: { orderId: result.order.id }, data: { providerPaymentId: checkout.order_id } }); return NextResponse.json({ checkoutUrl: checkout.checkout_url });
 } catch (error) { if (orderId) await prisma.order.delete({ where: { id: orderId } }).catch(() => undefined); const reason = error instanceof Error ? error.message : ""; const message = reason === "TAMARA_NOT_CONFIGURED" ? "Tamara is not configured yet." : reason === "ADDRESS_NOT_FOUND" ? "Choose a saved delivery address before continuing." : reason === "PET_SOLD" ? "This pet has already found a home." : reason === "OUT_OF_STOCK" ? "One or more accessories are no longer in stock." : reason === "DELIVERY_UNAVAILABLE" ? "Delivery is not available for this address yet." : error instanceof TamaraError ? `Tamara could not start this payment: ${reason}` : "Tamara could not start this payment. Please choose another payment method."; return NextResponse.json({ message }, { status: 400 }); }
}
