import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/require-admin";
import { prisma } from "@/lib/prisma";
const schema = z.object({ rating: z.number().int().min(1).max(5).optional(), title: z.string().trim().max(160).nullable().optional(), comment: z.string().trim().min(3).max(5000).optional(), status: z.enum(["Pending", "Approved", "Rejected"]).optional(), rejectionReason: z.string().trim().max(500).nullable().optional(), rejectionNotes: z.string().trim().max(5000).nullable().optional() });
const include = { customer: true, product: { include: { images: { orderBy: { sortOrder: "asc" as const }, take: 1 } } }, order: true };
type Context = { params: Promise<{ id: string }> };
export async function GET(request: Request, { params }: Context) { if (!(await requireAdmin(request))) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const review = await prisma.review.findUnique({ where: { id: (await params).id }, include }); return review ? NextResponse.json(review) : NextResponse.json({ message: "Review not found." }, { status: 404 }); }
export async function PATCH(request: Request, { params }: Context) { if (!(await requireAdmin(request))) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ message: "Please provide valid review changes." }, { status: 400 }); const update = { ...parsed.data, ...(parsed.data.status && parsed.data.status !== "Pending" ? { moderatedAt: new Date(), moderatedBy: "Admin" } : {}) }; const review = await prisma.review.update({ where: { id: (await params).id }, data: update, include }).catch(() => null); return review ? NextResponse.json(review) : NextResponse.json({ message: "Review not found." }, { status: 404 }); }
export async function DELETE(request: Request, { params }: Context) { if (!(await requireAdmin(request))) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const review = await prisma.review.delete({ where: { id: (await params).id } }).catch(() => null); return review ? NextResponse.json({ message: "Review deleted successfully." }) : NextResponse.json({ message: "Review not found." }, { status: 404 }); }
