import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/require-admin";
import { prisma } from "@/lib/prisma";
const schema = z.object({ name: z.string().trim().min(2).optional(), phone: z.string().trim().min(3).optional(), isActive: z.boolean().optional(), adminNotes: z.string().trim().max(5000).optional() });
type Context = { params: Promise<{ id: string }> };
export async function GET(request: Request, { params }: Context) { if (!(await requireAdmin(request))) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const customer = await prisma.customer.findUnique({ where: { id: (await params).id }, include: { orders: { include: { items: true }, orderBy: { createdAt: "desc" } }, reviews: { include: { product: true }, orderBy: { createdAt: "desc" } } } }); return customer ? NextResponse.json(customer) : NextResponse.json({ message: "Customer not found." }, { status: 404 }); }
export async function PATCH(request: Request, { params }: Context) { if (!(await requireAdmin(request))) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ message: "Please provide valid customer details." }, { status: 400 }); const customer = await prisma.customer.update({ where: { id: (await params).id }, data: parsed.data }).catch(() => null); return customer ? NextResponse.json(customer) : NextResponse.json({ message: "Customer not found." }, { status: 404 }); }
export async function DELETE(request: Request, { params }: Context) { if (!(await requireAdmin(request))) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const customer = await prisma.customer.delete({ where: { id: (await params).id } }).catch(() => null); return customer ? NextResponse.json({ message: `Customer \"${customer.name}\" deleted successfully.` }) : NextResponse.json({ message: "Customer not found." }, { status: 404 }); }
