import { NextResponse } from "next/server";
import { getCustomerSession } from "@/lib/auth/customer-session";
import { getAdminNotificationEmail } from "@/lib/auth/admin-auth-server";
import { sendOrderConfirmationEmails } from "@/lib/email/order-confirmation";
import { authoriseTamaraOrder } from "@/lib/payments/tamara";
import { prisma } from "@/lib/prisma";

export async function POST(_request: Request, { params }: { params: Promise<{ orderNumber: string }> }) {
 const session = await getCustomerSession(); if (!session?.sub) return NextResponse.json({ message: "Please sign in to confirm this payment." }, { status: 401 }); const { orderNumber } = await params;
 try { const order = await prisma.order.findFirst({ where: { orderNumber, customerId: session.sub }, include: { payment: true, items: { include: { product: true } }, shippingAddress: true } }); if (!order?.payment?.providerPaymentId || order.payment.provider !== "Tamara") throw new Error("ORDER_NOT_FOUND"); if (order.paymentStatus !== "Paid") await authoriseTamaraOrder(order.payment.providerPaymentId); const completed = await prisma.$transaction(async (tx) => { const current = await tx.order.findUnique({ where: { id: order.id }, include: { items: { include: { product: true } }, shippingAddress: true } }); if (!current) throw new Error("ORDER_NOT_FOUND"); if (current.paymentStatus === "Paid") return { order: current, newlyPaid: false }; for (const item of current.items) { if (!item.product) continue; const updated = item.product.type === "Animal" ? await tx.product.updateMany({ where: { id: item.productId ?? "", isSold: false }, data: { isSold: true } }) : await tx.product.updateMany({ where: { id: item.productId ?? "", quantity: { gte: item.quantity } }, data: { quantity: { decrement: item.quantity } } }); if (updated.count !== 1) throw new Error(item.product.type === "Animal" ? "PET_SOLD" : "OUT_OF_STOCK"); } const paid = await tx.order.update({ where: { id: current.id }, data: { paymentStatus: "Paid", orderStatus: "Confirmed" }, include: { items: true, shippingAddress: true } }); await tx.payment.update({ where: { orderId: current.id }, data: { status: "Paid", paidAt: new Date(), failureCode: null, failureMessage: null, failedAt: null } }); return { order: paid, newlyPaid: true }; }); if (completed.newlyPaid) void sendOrderConfirmationEmails(completed.order, await getAdminNotificationEmail()).catch(console.error); return NextResponse.json({ orderNumber, paymentStatus: "Paid" });
 } catch (error) { console.error("Tamara confirmation failed", error); return NextResponse.json({ message: "Tamara has not confirmed this payment yet. Please wait a moment and try again." }, { status: 400 }); }
}
